app = "fly-jad-bot"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "sin"
swap_size_mb = 512

[env]
PORT = "41641"

[experimental]
  auto_rollback = false
  private_network = true

[vm]
  memory = "256mb"

[mounts]
  source = "tailscale_data"
  destination = "/var/lib/tailscale"

[[services]]
  internal_port = 41641
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  protocol = "udp"

  [[services.ports]]
    port = 41641
    handlers = []
    protocol = "udp"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"