app = "fly-jad-bot"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "sin"
swap_size_mb = 512

[env]
PORT = "41641"
# create a reusable auth key and set it:
# flyctl secrets set TAILSCALE_AUTH_KEY=tskey-...
# ephemeral keys are hardly working for use as exit node as they are ipv6 only

[experimental]
  auto_rollback = false
  private_network = true

[vm]
  memory = "256mb"

[mounts]
  source = "tailscale_data"
  destination = "/var/lib/tailscale"

[[services]]
internal_port = 41641
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
protocol = "udp"

[[services.ports]]
port = 41641

[services.concurrency]
hard_limit = 100
soft_limit = 75
type = "connections"
